<nav id="nav">
    <a href="#" id="respmenu"><i class="fas fa-bars"></i> IZBORNIK</a>
    <ul>
		<li>
			<a href="/the-best-hotels-in-neum.html" target="_blank">HOTELI</a>
		</li>
		<li>
			<a href="/the-best-apartments-in-neum.html" target="_blank">APARTMANI</a>
		</li>
		<li>
			<a href="/the-best-villas-in-neum.html" target="_self">VILLE</a>
		</li>
        <li>
			<a href="/the-best-rooms-in-neum.html" target="_self">SOBE</a>
		</li>
		<li>
			<a href="/the-best-homes-in-neum.html" target="_self">KUĆE ZA ODMOR</a>
		</li> 
		<li>
			<a href="/the-best-restaurants-in-neum.html" target="_self">RESTORANI</a>
		</li >
		
		<li><a href='/rent-a-car-neum.html' target="_self">RENT A CAR</a></li>
		<!-- Link to open the modal -->   
		<li id="nav_right">
			<?php
				include 'nav_moduls/nav_right_nav.php';
			?>
		</li>
	</ul>
</nav>
	 