<a class="weatherwidget-io" href="https://forecast7.com/hr/42d9217d62/neum/" data-label_1="NEUM" data-label_2="VRIJEME" data-font="Roboto" data-theme="weather_one" >NEUM VRIJEME</a>
<script>
!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://weatherwidget.io/js/widget.min.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','weatherwidget-io-js');
</script>